[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqlnd", "php83Extensions.mbstring", "php83Extensions.session", "php83Extensions.fileinfo"]

[phases.build]
cmds = ["mkdir -p /app/database", "mkdir -p /app/public/assets/img/uploads"]

[start]
cmd = "php -S 0.0.0.0:8000 -t /app/public /app/public/router.php"
